apiVersion: v1
kind: Service
metadata:
  name: {{ include "single-elasticsearch.fullname" . }}-kibana
  labels:
    app.kubernetes.io/name: {{ include "single-elasticsearch.name" . }}
    helm.sh/chart: {{ include "single-elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "single-elasticsearch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
